version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:6.0
    container_name: wedesihomes-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: wedesihomes
    volumes:
      - mongo-data:/data/db

  # Backend API
  api:
    build: ./server
    container_name: wedesihomes-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongo:27017/wedesihomes?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend
  client:
    build: ./client
    container_name: wedesihomes-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data: